[project]
name = "creditscore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter",
    "matplotlib",
    "numexpr",
    "numpy",
    "pandas",
    "pillow",
    "pip",
    "protobuf",
    "psutil",
    "scikit-learn",
    "scipy",
    "sympy",
    "tensorflow",
]
